# Generated by Django 4.2.11 on 2026-06-03 15:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "generated_by",
                    models.CharField(default="gemini-1.5-flash", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap",
                        to="analysis.skillgapreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roadmap",
                "verbose_name_plural": "Roadmaps",
                "db_table": "roadmaps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
                ("week_number", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "gap_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roadmap_items",
                        to="analysis.gapitem",
                    ),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="roadmap.roadmap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roadmap Item",
                "verbose_name_plural": "Roadmap Items",
                "db_table": "roadmap_items",
                "ordering": ["week_number"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=1000)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("freecodecamp", "FreeCodeCamp"),
                            ("roadmap_sh", "Roadmap.sh"),
                            ("docs", "Documentation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("article", "Article"),
                            ("course", "Course"),
                            ("documentation", "Documentation"),
                        ],
                        default="article",
                        max_length=20,
                    ),
                ),
                (
                    "roadmap_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="roadmap.roadmapitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
                "db_table": "resources",
            },
        ),
    ]
