# Generated by Django 4.2.11 on 2026-06-03 15:35

from django.db import migrations, models
import django.db.models.deletion
from pgvector.django import VectorField
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CVUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_url", models.URLField(max_length=500)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CV Upload",
                "verbose_name_plural": "CV Uploads",
                "db_table": "cv_uploads",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(max_length=255)),
                ("confidence_score", models.FloatField(default=1.0)),
                ("skill_vector", VectorField(dimensions=384)),
                (
                    "cv_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_skills",
                        to="parser.cvupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extracted Skill",
                "verbose_name_plural": "Extracted Skills",
                "db_table": "extracted_skills",
                "ordering": ["-confidence_score"],
            },
        ),
    ]
