# Generated by Django 4.2.11 on 2026-06-03 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GapItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
                ("demand_frequency", models.FloatField()),
                ("similarity_score", models.FloatField()),
                ("priority_rank", models.IntegerField()),
            ],
            options={
                "verbose_name": "Gap Item",
                "verbose_name_plural": "Gap Items",
                "db_table": "gap_items",
                "ordering": ["priority_rank"],
            },
        ),
        migrations.CreateModel(
            name="SkillGapReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("readiness_score", models.FloatField(default=0.0)),
                ("total_jobs_matched", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Skill Gap Report",
                "verbose_name_plural": "Skill Gap Reports",
                "db_table": "skill_gap_reports",
                "ordering": ["-generated_at"],
            },
        ),
    ]
