# Generated by Django 4.2.11 on 2026-06-03 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parser", "0001_initial"),
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillgapreport",
            name="cv_upload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gap_reports",
                to="parser.cvupload",
            ),
        ),
    ]
