# Generated by Django 4.2.11 on 2026-06-03 15:35

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("company", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[("merojob", "Merojob"), ("kumarijob", "Kumarijob")],
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(max_length=1000, unique=True)),
                (
                    "experience_level",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Job Posting",
                "verbose_name_plural": "Job Postings",
                "db_table": "job_postings",
                "ordering": ["-scraped_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapeJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("merojob", "Merojob"), ("kumarijob", "Kumarijob")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("jobs_found", models.IntegerField(default=0)),
                ("jobs_saved", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Scrape Job",
                "verbose_name_plural": "Scrape Jobs",
                "db_table": "scrape_jobs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="JobSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(max_length=255)),
                ("is_required", models.BooleanField(default=True)),
                ("skill_vector", pgvector.django.vector.VectorField(dimensions=384)),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_skills",
                        to="scraper.jobposting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Skill",
                "verbose_name_plural": "Job Skills",
                "db_table": "job_skills",
            },
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["source", "is_active"], name="job_posting_source_977638_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["-scraped_at"], name="job_posting_scraped_6ecfb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobskill",
            index=models.Index(
                fields=["normalized_name"], name="job_skills_normali_ac1e4e_idx"
            ),
        ),
    ]
